### ISSUE TITLE
Logic for handling ANR's during app installation process. 

### ISSUE THREAD

**Issue by ethancox127** [killuhwhale/appium#1]
ANR's during the app installation process when searching for an app or searching for the app icon cause the app installation to fail at that step because it is not repeated after clearing the ANR.  The logic needs to be reworked to restart the app installation process from the step where the ANR occurred so it is completed properly.

**Comment by killuhwhale** [comment]
I think we can use the same technique that we use when finding an invalid App name from the Web Playstore which is to recurse when finding a specific error and limit the number of attempts.
