### ISSUE TITLE
Unable to get automation run to complete at the office.

### ISSUE THREAD

**Issue by ethancox127** [killuhwhale/appium#3]
When running the automation script at the office on a Chromebook with dual boot Ubuntu set up or from the Debian container of a Chromebook the devices seem to "restart" at some point usually between 10pm and 1am.  The dual boot Ubuntu device shows the "ChromeOS verification is off" screen and must be flashed using the "fix flags" binary before Ubuntu can be run again and the boot loader can be reached by pressing "CTRL + L".  The Debian container appeared to be updating itself causing the automation run to stop but it has been difficult to track down logs for this issue so far.

**Comment by killuhwhale** [comment]
We now have a dedicated laptop with Ubuntu as the only OS. Hopefully we will not encounter this on this device.

**Comment by ethancox127** [comment]
When did we get that laptop and where is it?

**Comment by killuhwhale** [comment]
I ran the top 280 B* apps against the latest version and successfully completed on 2 devices. So 546 apps were ran through successfully.

Hopefully, office runs will work too now

**Comment by ethancox127** [comment]
There appears to be no issue running the automation to completion in the office anymore, closing issue.
