### ISSUE TITLE
Incorrect error step shown for app that fail to install properly.

### ISSUE THREAD

**Issue by ethancox127** [killuhwhale/appium#4]
On ARC-R Helios apps that are not available on the device are appearing to report clicking the install button as the step in the installation process where they failed.

**Comment by ethancox127** [comment]
Also appears to be true for ARC-P Kevin.

**Comment by killuhwhale** [comment]
To make this more simple, I believe that we should put all reasons and status into one column.

The status is simply pass or fail but we can just used more status numbers to indicate the status and thus infer the reason.

So lets remove the reason & invalid column and add more statuses. 
Failure status is 0 and lower, passing status is 1 or higher.



Also, I think this is just an issue with semantics.

The error  "Failed: Click install button" indicates there was a failure during the  step:  Click install button.
So it doesn't mean the reason for failure was clicking install button, rather, there was a failure during the step: Click install button (as this is the goal of this step)

Again, the status should help clear things up.

Closing for now as fixed.
