### ISSUE TITLE
Reporting should be updated to include more results on the front end.

### ISSUE THREAD

**Issue by ethancox127** [killuhwhale/appium#5]
Specifically, it would be good to add the three steps in the current app installation process as reasons that can be displayed to the user instead of just "Not installed - Failed to open".

**Comment by killuhwhale** [comment]
Yes, we also need to add more info regarding the app.

From our manager:
1. We can have summary page which will have details like Total apps tested - Passed, failed. 
2. For each app we need all info like App Category, version, Test cases executed

We will focus on this once the automation runs run smoothly.

**Comment by killuhwhale** [comment]
Closing since we have added AppStatus to incorporate more statuses including the installation process errors.

Also, app_type, app_version are now added to the reported data.
